version: '3.4'

services:
  micromachines:
    image: ${DOCKER_REGISTRY-}micromachines
    build:
      context: .
      dockerfile: MicroMachines/Dockerfile
    ports: [2000:80]

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports: [2001:80]

  stockservice:
    image: ${DOCKER_REGISTRY-}stockservice
    build:
      context: .
      dockerfile: StockService/Dockerfile
    ports: [2002:80]

