version: '3.4'

services:
  micromachines:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  orderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  stockservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

